import requests
import os
from dotenv import load_dotenv 

load_dotenv()
API_KEY = os.getenv("PERPLEXITY_API_KEY")
if not API_KEY:
    raise ValueError("API key not found in .env file. Please add PERPLEXITY_API_KEY to your .env file.")

BASE_URL = "https://api.perplexity.ai"

def generate_sentences(input_text):
    
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    
    payload = {
    "model": "llama-3.1-sonar-small-128k-online",
    "messages": [
        {
            "role": "system",
            "content": (
                "CRITICAL RULE: Return ONLY the corrected sentence. No explanations, no input/output labels.\n"
                "1. Return ONLY the corrected sentence - no explanations, labels, or quotes\n"
                "2. NEVER change original words or grammar structures\n"
                "3. NEVER add, remove, or modify words\n"
                "4. ONLY fix spelling errors and join spaced letters\n"
                "5. Add punctuation ONLY when clearly needed\n"
                "6. Maintain ALL original word forms exactly as given\n"
                "7. Keep exact same sentence structure\n"
                "8. Preserve word order exactly as input\n"
                "9. Keep formal/informal tone as provided\n"
                "10. No semantic or meaning changes\n"
                "11. Keep known acronyms exactly as they are (BMW stays BMW)\n"
                "12. Add period after single words and acronyms\n"
                "13. NEVER convert acronyms to words\n"
                "14. Fix common typing errors and misspellings\n"
                "15. Add appropriate punctuation\n"
                "16. Convert repeated letters only if they're typos (like 'helllo' to 'hello')"
                "19. Maintain proper sentence case"
                "20. Handle contractions properly (dont -> don't, cant -> can't)"
                "\nExamples:\n"
                "Input: D O N O T C R Y N O W\n"
                "Output: Do Not Cry Now.\n"
                "\nInput: I A M G O I N G H O M E\n"
                "Output: I Am Going Home.\n"
                "\nInput: W H E R E A R E Y O U G O I N G\n"
                "Output: Where Are You Going?\n"
                "\nInput: H E L L O W O R L D\n"
                "Output: Hello World.\n"
                "\nInput: T H I S I S A T E S T\n"
                "Output: This Is A Test.\n"
                "\nInput: G O O D M O R N I N G\n"
                "Output: Good Morning.\n"
                "\nInput: S E E Y O U T O M O R R O W\n"
                "Output: See You Tomorrow.\n"
                "\nInput: H A V E A N I C E D A Y\n"
                "Output: Have A Nice Day.\n"
                "\nInput: T H A N K Y O U V E R Y M U C H\n"
                "Output: Thank You Very Much.\n"
                "\nInput: P L E A S E H E L P M E\n"
                "Output: Please Help Me.\n"
                "\nInput: I L O V E P R O G R A M M I N G\n"
                "Output: I Love Programming.\n"
                "\nInput: W E A R E W O R K I N G\n"
                "Output: We Are Working.\n"
                "\nInput: S H E I S D A N C I N G\n"
                "Output: She Is Dancing.\n"
                "\nInput: T H E Y A R E P L A Y I N G\n"
                "Output: They Are Playing.\n"
                "\nInput: H E W A S H E R E\n"
                "Output: He Was Here.\n"
                "\nInput: W E W E R E T H E R E\n"
                "Output: We Were There.\n"
                "\nInput: I T I S R A I N I N G\n"
                "Output: It Is Raining.\n"
                "\nInput: T H E S U N I S S H I N I N G\n"
                "Output: The Sun Is Shining.\n"
                "\nInput: B I R D S A R E F L Y I N G\n"
                "Output: Birds Are Flying.\n"
                "\nInput: W H A T I S Y O U R N A M E\n"
                "Output: What Is Your Name?\n"
                "\nInput: H O W A R E Y O U\n"
                "Output: How Are You?\n"
                "\nInput: N I C E T O M E E T Y O U\n"
                "Output: Nice To Meet You.\n"
                "\nInput: S E E Y O U L A T E R\n"
                "Output: See You Later.\n"
                "\nInput: H A V E F U N\n"
                "Output: Have Fun.\n"
                "\nInput: T A K E C A R E\n"
                "Output: Take Care.\n"
                "\nInput: B E S A F E\n"
                "Output: Be Safe.\n"
                "\nInput: G O O D L U C K\n"
                "Output: Good Luck.\n"
                "\nInput: W E L C O M E B A C K\n"
                "Output: Welcome Back.\n"
                "\nInput: S T A Y H O M E\n"
                "Output: Stay Home.\n"
                "\nInput: B E H A P P Y\n"
                "Output: Be Happy.\n"
                "\nExamples:\n"
                "Input: M A C H I N E L E A U N I N G\n"
                "Output: Machine Learning.\n"
                "\nInput: C A N Y O U F Y I X T H O E O L D U V A N\n"
                "Output: Can you fix the old van?\n"
                "\nInput: A R T I F I C A L I N T E L I G E N S\n"
                "Output: Artificial Intelligence.\n"
                "\nInput: W H E R E I S S T H E N E W C A R R\n"
                "Output: Where is the new car?\n"
                "\nInput: S O F T W E R E N G I N E R\n"
                "Output: Software Engineer.\n"
                "\nInput: H E L P M E E W I T H T H I S S C O D E\n"
                "Output: Help me with this code.\n"
                "\nInput: D A T A S C I E N S E\n"
                "Output: Data Science.\n"
                "\nInput: T H E Y Y A R E W O R K I N G G H A R D\n"
                "Output: They are working hard.\n"
                "\nInput: C L O U D C O M P U T I G\n"
                "Output: Cloud Computing.\n"
                "\nInput: W H A T T I S S Y O U R N A M E E\n"
                "Output: What is your name?\n"
                "\nInput: F U L L S T A K D E V E L O P E R\n"
                "Output: Full Stack Developer.\n"
                "\nInput: P L E A S E E O P E N T H E D O O R R\n"
                "Output: Please open the door.\n"
                "\nInput: W E B D E V E L O P M E N T T\n"
                "Output: Web Development.\n"
                "\nInput: I L O V E E P R O G R A M M I N G G\n"
                "Output: I love programming.\n"
                "\nInput: D A T A B A S E Q U E R Y Y\n"
                "Output: Database Query.\n"
                "\nInput: D O Y O U U L I K E C O F F E E E\n"
                "Output: Do you like coffee?\n"
                "\nInput: S Y S T E M D E S I G N N\n"
                "Output: System Design.\n"
                "\nInput: L E T S S G O T O T H E P A R K K\n"
                "Output: Lets go to the park."
                "\nSingle Word Examples:\n"
                "Input: D O N E\n"
                "Output: Done.\n"
                "\nInput: H E L L O\n"
                "Output: Hello.\n"
                "\nInput: W O R K\n"
                "Output: Work.\n"
                "\nInput: S L E E P\n"
                "Output: Sleep.\n"
                "\nInput: C O D E\n"
                "Output: Code.\n"
                "\nAcronym Examples:\n"
                "Input: B M W\n"
                "Output: BMW.\n"
                "\nInput: I B M\n"
                "Output: IBM.\n"
                "\nInput: N A S A\n"
                "Output: NASA.\n"
                "\nInput: F B I\n"
                "Output: FBI.\n"
                "\nInput: C I A\n"
                "Output: CIA.\n"
                "\nInput: N B A\n"
                "Output: NBA.\n"
                "\nInput: U S A\n"
                "Output: USA.\n"
                "\nInput: U K\n"
                "Output: UK.\n"
                "\nInput: U N\n"
                "Output: UN.\n"
                "\nInput: M I T\n"
                "Output: MIT.\n"
                "\nInput: N F L\n"
                "Output: NFL.\n"
                "\nInput: W H O\n"
                "Output: WHO.\n"
                "\nInput: N O S\n"
                "Output: NOS.\n"
                "\nInput: R A M\n"
                "Output: RAM.\n"
                "\nInput: C P U\n"
                "Output: CPU.\n"
                "\nInput: G P U\n"
                "Output: GPU.\n"
                "\nMixed Examples:\n"
                "Input: I W O R K A T I B M\n"
                "Output: I Work At IBM.\n"
                "\nInput: M Y B M W I S N E W\n"
                "Output: My BMW Is New.\n"
                "\nInput: T H E C I A A N D F B I\n"
                "Output: The CIA And FBI.\n"
                "\nInput: N A S A A N D I S R O\n"
                "Output: NASA And ISRO.\n"
                "\nTyping Error Examples:\n"
                "Input: HELLOZ\n"
                "Output: Hello.\n"
                "\nInput: GOODZ\n"
                "Output: Good.\n"
                "\nInput: THANKZ\n"
                "Output: Thanks.\n"
                "\nInput: NICEE\n"
                "Output: Nice.\n"
                "\nInput: GREATT\n"
                "Output: Great.\n"
                "\nMisspelling Examples:\n"
                "Input: Quewn\n"
                "Output: Queen.\n"
                "\nInput: Programing\n"
                "Output: Programming.\n"
                "\nInput: Enginear\n"
                "Output: Engineer.\n"
                "\nInput: Computar\n"
                "Output: Computer.\n"
                "\nInput: Softwar\n"
                "Output: Software.\n"
                "\nMixed Error Examples:\n"
                "Input: TESZT\n"
                "Output: Test.\n"
                "\nInput: CODINGG\n"
                "Output: Coding.\n"
                "\nInput: SLEAPING\n"
                "Output: Sleeping.\n"
                "\nInput: STUDYYING\n"
                "Output: Studying.\n"
                "\nInput: WORKKING\n"
                "Output: Working.\n"
                "\nCommon Letter Substitutions:\n"
                "Input: KODING\n"
                "Output: Coding.\n"
                "\nInput: PHISHING\n"
                "Output: Fishing.\n"
                "\nInput: SKOOL\n"
                "Output: School.\n"
                "\nInput: LITE\n"
                "Output: Light.\n"
                "\nInput: NITE\n"
                "Output: Night.\n"
                "\nExtra Letter Examples:\n"
                "Input: RUNNINGG\n"
                "Output: Running.\n"
                "\nInput: SWIMMMING\n"
                "Output: Swimming.\n"
                "\nInput: DANCCING\n"
                "Output: Dancing.\n"
                "\nInput: PLAYYING\n"
                "Output: Playing.\n"
                "\nMissing Letter Examples:\n"
                "Input: PROGAM\n"
                "Output: Program.\n"
                "\nInput: DEVLOPER\n"
                "Output: Developer.\n"
                "\nInput: ENGINER\n"
                "Output: Engineer.\n"
                "\nMixed Errors in Sentences:\n"
                "Input: I A M A PROGRAMMMER\n"
                "Output: I Am A Programmer.\n"
                "\nInput: S H E I S DANSING\n"
                "Output: She Is Dancing.\n"
                "\nInput: T H E Y R PLAYYING\n"
                "Output: They Are Playing.\n"
                "\nMissing Letter Examples:\n"
                "Input: S I N G G A G E\n"
                "Output: Sign Language.\n"
                "\nInput: D E F A\n"
                "Output: Deaf.\n"
                "\nInput: H N A D\n"
                "Output: Hand.\n"
                "\nInput: F I N G R E\n"
                "Output: Finger.\n"
                "\nInput: G E S T R U E\n"
                "Output: Gesture.\n"
                "\nInput: S P E L L I G N\n"
                "Output: Spelling.\n"
                "\nInput: C O M M U N I C T E\n"
                "Output: Communicate.\n"
                "\nInput: E X P R E S S N I O\n"
                "Output: Expression.\n"
                "\nInput: V I S U L A\n"
                "Output: Visual.\n"
                "\nInput: M O V E M N E T\n"
                "Output: Movement.\n"
                "\nCommonly Confused Letters:\n"
                "Input: B D (commonly confused in signing)\n"
                "Output: B.\n"
                "\nInput: M W\n"
                "Output: M.\n"
                "\nInput: N Z\n"
                "Output: N.\n"
                "\nInput: P Q\n"
                "Output: P.\n"
                "\nInput: D B\n"
                "Output: D.\n"
                "\nInput: S Z\n"
                "Output: S.\n"
                "\nInput: E Three\n"
                "Output: E.\n"
                "\nInput: C O\n"
                "Output: C.\n"
                "\nInput: V U\n"
                "Output: V.\n"
                "\nInput: G C\n"
                "Output: G.\n"
                "\nMore Examples:\n"
                "Input: F E E L I G N\n"
                "Output: Feeling.\n"
                "\nInput: M O R N I M G\n"
                "Output: Morning.\n"
                "\nInput: T H A M K\n"
                "Output: Thank.\n"
                "\nInput: W A T E R N\n"
                "Output: Water.\n"
                "\nInput: P L E A S N E\n"
                "Output: Please.\n"
                "\nInput: H E L L M O\n"
                "Output: Hello.\n"
                "\nInput: G O O D M B Y E\n"
                "Output: Goodbye.\n"
                "\nInput: S I G M N\n"
                "Output: Sign.\n"
                "\nInput: F R I E M N D\n"
                "Output: Friend.\n"
                "\nInput: T E A C H M E R\n"
                "Output: Teacher.\n"
                "\nInput: L O V E L\n"
                "Output: Love.\n"
                "\nInput: H A P P Y P\n"
                "Output: Happy.\n"
                "\nInput: S O R R Y R\n"
                "Output: Sorry.\n"
                "\nInput: T H A N K S K\n"
                "Output: Thanks.\n"
                "\nInput: H E L P H\n"
                "Output: Help.\n"
                "\nInput: W A N T W\n"
                "Output: Want.\n"
                "\nInput: N E E D N\n"
                "Output: Need.\n"
                "\nInput: G I V E G\n"
                "Output: Give.\n"
                "\nInput: S E E S\n"
                "Output: See.\n"
                "\nInput: M E E T M\n"
                "Output: Meet.\n"
                "\nDirectional Examples:\n"
                "Input: U P D O W N W\n"
                "Output: Up Down.\n"
                "\nInput: L E F T R I G H L\n"
                "Output: Left Right.\n"
                "\nInput: F R O N T B A C K F\n"
                "Output: Front Back.\n"
                "\nInput: H I G H L O W H\n"
                "Output: High Low.\n"
                "\nInput: I N O U T T\n"
                "Output: In Out.\n"
                "\nInput: T O P B O T T O M P\n"
                "Output: Top Bottom.\n"
                "\nInput: N E A R F A R R\n"
                "Output: Near Far.\n"
                "\nInput: B E F O R E A F T E R E\n"
                "Output: Before After.\n"
                "\nInput: A B O V E B E L O W W\n"
                "Output: Above Below.\n"
                "\nInput: S I D E T O S I D E E\n"
                "Output: Side To Side.\n"
            )
        },
        {
            "role": "user",
            "content": input_text
        }
    ],
    "temperature": 0.0,
    "top_p": 1.0,
    "max_tokens": len(input_text.split()) + 15,
    "stop": None,
    "n": 1,
    "logit_bias": {}
}

    try:
        response = requests.post(f"{BASE_URL}/chat/completions", json=payload, headers=headers)
        response.raise_for_status()
        result = response.json()
        return result.get("choices", [{}])[0].get("message", {}).get("content", "No response generated.")
    
    except requests.exceptions.RequestException as e:
        return f"An error occurred: {e}"

# Example usage
if __name__ == "__main__":
    input_text = "A L P H O A Z B E T"
    output = generate_sentences(input_text)
    
    print("Input Text:", input_text)
    print("Generated Sentences:", output)
